### ISSUE TITLE
Interactions between data types Ruby vs JavaScript

### ISSUE THREAD

**Issue by laramontana** [learn-co-curriculum/js-basics-data-types-readme#1]
The third paragraph of 'Interactions between data types' part sound a bit confusing. 

> Other languages are more forgiving. 

as if there is going to be a comparison between forgiving JS and some other more strict language. 

> For example, instead of throwing an error when an integer (3) is added to a floating-point number (0.14159), Ruby will simply convert the integer into a floating-point number and correctly calculate the sum

Both Ruby and JS correctly calculate the sum. Maybe it would be clearer to compare JS and some language which actually would throw an error?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
