### ISSUE TITLE
Missing word in `typeof` section

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/js-basics-data-types-readme#5]
The section "Demonstrate Basic Type Checking with the `typeof` Operator" is missing the word "one" in the second sentence. It should be:

> **CAREFUL** `typeof` is an operator, just like `+` or `!`. We get used to operators
> being only one character, but JavaScript (and many other languages) have operators
> with more than **_one_** character. As such, **we don't need parentheses with `typeof`**. That
> said, JavaScript also supports `()` after `typeof`, but it's commonly not done.

**Comment by sgharms** [comment]
Thanks, fixed!
