### ISSUE TITLE
Minor typo in "Think About This"

### ISSUE THREAD

**Issue by afteralec** [learn-co-curriculum/js-basics-data-types-readme#9]
Partway down the README, just beneath the `typeof` example for numbers:

>**Think About This:** As JavaScript has become a language for the back-end as well as the front-end, it's imprecision 
around numbers keep it from entering many banking or engineering applications where precision is vital.

Typo:

> it's imprecision

should be:

> its imprecision

I know, sorry.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

Thank you for contributing to a learn-co-curriculum repository! 💙
